RIILAutotest/urls.py
from django.contrib import admin
from django.urls import path

from apitest import views
from product import proviews

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', views.login),
    path('home/', views.home),
    path('logout/', views.logout),
    path('product_manage/', proviews.product_manage),
    path('apitest_manage/', views.apitest_manage),
    path('apistep_manage/', views.apistep_manage),
]

apitest/models.py
# -*- coding:utf-8 -*-
from django.db import models
from product.models import Product

# Create your models here.

class Apitest(models.Model):
    Product = models.ForeignKey('product.Product',on_delete=models.CASCADE,null=True)        # 关联产品id
    apitestname = models.CharField('流程接口名称',max_length=64)  # 流程接口 测试场景
    apitestdesc = models.CharField('描述',max_length=64,null=True)  # 流程接口 描述
    apitester = models.CharField('测试负责人',max_length=16)            # 执行人
    apitestresult = models.BooleanField('测试结果')                 # 流程接口测试结果
    create_time = models.DateTimeField('创建时间',auto_now=True)  # 创建时间-自动获取当前时间
    class Meta:
        verbose_name = '流程场景接口'
        verbose_name_plural = '流程场景接口'
    def __str__(self):
        return self.apitestname

class Apistep(models.Model):
    Apitest = models.ForeignKey('Apitest',on_delete=models.CASCADE,)        # 关联接口id
    apistep = models.CharField('测试步聚',max_length=100,null=True)         # 测试步聚
    apiname = models.CharField('接口名称',max_length=100)         # 接口名称描述
    apiurl = models.CharField('url地址',max_length=200)             # 地址
    REQUEST_METHOD = (('get', 'get'),('post', 'post'),('put', 'put'),('delete', 'delete'),('patch', 'patch'))
    apiparamvalue = models.CharField('请求参数和值',max_length=800)    # 参数和值
    apimethod = models.CharField(verbose_name='请求方法',choices = REQUEST_METHOD,default='get',max_length=200,null=True)  # 请求方法
    apiresult = models.CharField('预期结果',max_length=200)         # 预期结果
    apiresponse = models.CharField('响应数据',max_length=5000,null=True)    # 响应数据
    apistatus = models.BooleanField('是否通过')                      # 测试结果
    create_time = models.DateTimeField('创建时间',auto_now=True)   # 创建时间-自动获取当前时间
    def __str__(self):
        return self.apistep

class Apis(models.Model):
    Product = models.ForeignKey('product.Product',on_delete=models.CASCADE,null=True)        # 关联产品id
    apiname = models.CharField('接口名称',max_length=100)         # 接口标题
    apiurl = models.CharField('url地址',max_length=200)             # 地址
    apiparamvalue = models.CharField('请求参数和值',max_length=800)    # 请求参数和值
    REQUEST_METHOD = (('get', 'get'),('post', 'post'),('put', 'put'),('delete', 'delete'),('patch', 'patch'))
    apimethod = models.CharField(verbose_name='请求方法',choices = REQUEST_METHOD,default='get',max_length=200,null=True)  # 请求方法
    apitester = models.CharField('测试负责人',max_length=16,null=True)            # 执行人
    apiresult = models.CharField('预期结果',max_length=200)         # 预期结果
    apiresponse = models.CharField('响应数据',max_length=5000,null=True)    # 响应数据
    apistatus = models.BooleanField('是否通过')                      # 测试结果
    create_time = models.DateTimeField('创建时间',auto_now=True)   # 创建时间-自动获取当前时间
    class Meta:
        verbose_name = '单一场景接口'
        verbose_name_plural = '单一场景接口'
    def __str__(self):
        return self.apiname

product/models.py
from django.db import models


# Create your models here.
class Product(models.Model):
    productname = models.CharField('产品名称', max_length=64)
    productdesc = models.CharField('产品描述', max_length=200)
    producter = models.CharField('产品负责人', max_length=200, null=True)
    create_time = models.DateTimeField('创建时间', auto_now=True)

    class Meta:
        verbose_name = '产品管理'
        verbose_name_plural = '产品管理'

    def __str__(self):
        return self.productname

apitest/views.py
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render
from apitest.models import Apitest,Apistep,Apis
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.
def login(request):
    if request.POST:
        username = password = ''
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = auth.authenticate(username=username, password=password)
        if user is not None and user.is_active:
            auth.login(request, user)
            request.session['user'] = username
            response = HttpResponseRedirect('/home/')
            return response
        else:
            return render(request, 'login.html', {'error': 'username or password error'})
    return render(request, 'login.html')


def logout(request):
    auth.logout(request)
    return render(request, 'login.html')


def home(request):
    return render(request, "home.html")


# 流程接口管理
@login_required
def apitest_manage(request):
    apitest_list = Apitest.objects.all()  # 获取所有接口测试用例
    apitest_count = Apitest.objects.all().count()  # 统计产品数
    username = request.session.get('user', '')  # 读取浏览器登录session
    paginator = Paginator(apitest_list, 8)  # 生成paginator对象,设置每页显示8条记录
    page = request.GET.get('page', 1)  # 获取当前的页码数,默认为第1页
    currentPage = int(page)  # 把获取的当前页码数转换成整数类型
    try:
        apitest_list = paginator.page(page)  # 获取当前页码数的记录列表
    except PageNotAnInteger:
        apitest_list = paginator.page(1)  # 如果输入的页数不是整数则显示第1页的内容
    except EmptyPage:
        apitest_list = paginator.page(paginator.num_pages)  # 如果输入的页数不在系统的页数中则显示最后一页的内容
    return render(request, "apitest_manage.html",
                  {"user": username, "apitests": apitest_list, "apitestcounts": apitest_count})  # 把值赋给apitestcounts这个变量


# 接口步聚管理
@login_required
def apistep_manage(request):
    username = request.session.get('user', '')
    apitestid = request.GET.get('apitest.id', None)
    apitest = Apitest.objects.get(id=apitestid)  # 获取所有接口测试用例
    apistep_list = Apistep.objects.all()
    return render(request, "apistep_manage.html", {"user": username, "apitest": apitest, "apisteps": apistep_list})


# 单一接口管理
@login_required
def apis_manage(request):
    username = request.session.get('user', '')
    apis_list = Apis.objects.all()
    apis_count = Apis.objects.all().count()  # 统计产品数
    paginator = Paginator(apis_list, 8)  # 生成paginator对象,设置每页显示8条记录
    page = request.GET.get('page', 1)  # 获取当前的页码数,默认为第1页
    currentPage = int(page)  # 把获取的当前页码数转换成整数类型
    try:
        apis_list = paginator.page(page)  # 获取当前页码数的记录列表
    except PageNotAnInteger:
        apis_list = paginator.page(1)  # 如果输入的页数不是整数则显示第1页的内容
    except EmptyPage:
        apis_list = paginator.page(paginator.num_pages)  # 如果输入的页数不在系统的页数中则显示最后一页的内容
    return render(request, "apis_manage.html",
                  {"user": username, "apiss": apis_list, "apiscounts": apis_count})  # 把值赋给apiscounts这个变量

apitest/templates/apistep_manage.html
<html lang="zh-CN">
<head>
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<link href="../static/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css" />

<script type="text/javascript" src="/admin/jsi18n/"></script>



<script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>

<script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
<script type="text/javascript" src="/static/admin/js/core.js"></script>

<script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
<script type="text/javascript" src="/static/admin/js/actions.js"></script>

<script type="text/javascript" src="/static/admin/js/urlify.js"></script>

<script type="text/javascript" src="/static/admin/js/prepopulate.js"></script>

<script type="text/javascript" src="/static/admin/js/vendor/xregexp/xregexp.js"></script>


    
<meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
    
<link rel="stylesheet" type="text/css" href="/static/admin/css/responsive.css" />
    


<meta name="robots" content="NONE,NOARCHIVE" />
<style> body{text-align:center} </style> 
<title>产品自动化测试平台</title>
</head>

<body role="document">
<!-- 导航栏-->
<nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
<div class="container">
<li class="active"><a style='color:white' href="/apis_manage/">单一接口</a></li> 
&nbsp;&nbsp;&nbsp;&nbsp;
<li><a style='color:white' href="/apitest_manage/">流程接口</a></li>
&nbsp;&nbsp;&nbsp;&nbsp;
<li class="active"><a style='color:white' href="/appcase_manage/">app用例</a></li>
&nbsp;&nbsp;&nbsp;&nbsp;
<li class="active"><a style='color:white' href="/webcase_manage/">web用例</a></li>
&nbsp;&nbsp;&nbsp;&nbsp;
<ul class="nav justify-content-center">  
</ul>

<ul class="nav justify-content-end" style="position:absolute; right:10px; bottom:0px; ">
<li class="nav-link"><a style='color:white' href="#">{{user}}</a></li>
<li class="nav-link"><a style='color:white' href="/logout/">退出</a></li>
</ul>
</div>
</nav>

<!-- 流程接口测试步聚-->
<div class="row" style="padding-top: 0px;">
<div class="col-md-12">
<table class="table table-striped">
<thead>

<tr>
<th>产品</th><th>所属用例</th><th>步聚</th><th>URL地址</th><th>参数值</th><th>方法</th><th>校验</th><th>结果</th><th>时间</th>
</tr>
</thead>
<tbody>
{% for apistep in apisteps %}
<tr>
{% if apistep.Apitest.id == apitest.id  %}
<td>{{ apistep.Apitest.Product.productname }}</td>
<td>case_{{ apistep.Apitest.id }}_{{ apistep.Apitest.apitestname }}</td>
<td>{{ apistep.apistep }}:{{ apistep.apiname }}</td>
<td>{{ apistep.apiurl }}</td>
<td>{{ apistep.apiparamvalue }}</td>
<td>{{ apistep.apimethod }}</td>
<td>{{ apistep.apiresult }}</td>
<td>{% if apistep.apistatus == 1 %}
<a style='color:green'>{{ apistep.apistatus }}</a> 
{% else %}
<a style='color:red'>{{ apistep.apistatus }}</a> 
{% endif %}
</td>
<td>{{ apistep.create_time }}</td>
{% else %}
{% endif %}
</tr>
{% endfor %}
</tbody>
</table>
</div>
</div>

<td>
<a style='color:light blue'  href="../apitest_manage/" >
<img src="/static/admin/img/icon-yes.svg" alt="返回"/>返回
</a>
</td>

<td>
<a style='color:light blue' class="related-widget-wrapper-link add-related" id="add_id_Apitest" href="../admin/apitest/apitest/{{ apitest.id  }}/change/?_to_field=id&_popup=1">
<img src="/static/admin/img/icon-changelink.svg"/>编辑</a>
</td>


</body>
</html>

apitest/templates/apitest_manage.html
<html lang="zh-CN">
<head>
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<title>产品自动化测试平台</title>
<link href="../static/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css" />

<script type="text/javascript" src="/admin/jsi18n/"></script>



<script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>

<script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
<script type="text/javascript" src="/static/admin/js/core.js"></script>

<script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
<script type="text/javascript" src="/static/admin/js/actions.js"></script>

<script type="text/javascript" src="/static/admin/js/urlify.js"></script>

<script type="text/javascript" src="/static/admin/js/prepopulate.js"></script>

<script type="text/javascript" src="/static/admin/js/vendor/xregexp/xregexp.js"></script>


    
<meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
    
<link rel="stylesheet" type="text/css" href="/static/admin/css/responsive.css" />
    


<meta name="robots" content="NONE,NOARCHIVE" />

</head>
<body role="document">
<!-- 导航栏-->
<nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
<div class="container">
<li class="active"><a style='color:white' href="/apis_manage/">单一接口</a></li> 
&nbsp;&nbsp;&nbsp;&nbsp;
<li><a style='color:white' href="/apitest_manage/">流程接口</a></li>
&nbsp;&nbsp;&nbsp;&nbsp;
<li class="active"><a style='color:white' href="/appcase_manage/">app用例</a></li>
&nbsp;&nbsp;&nbsp;&nbsp;
<li class="active"><a style='color:white' href="/webcase_manage/">web用例</a></li>
&nbsp;&nbsp;&nbsp;&nbsp;
<ul class="nav justify-content-center"> 

</ul>
<ul class="nav justify-content-end" style="position:absolute; right:10px; bottom:0px; ">
<li class="nav-link"><a style='color:white' href="#">{{user}}</a></li>
<li class="nav-link"><a style='color:white' href="/logout/">退出</a></li>
</ul>
</div>
</nav>
<!-- 搜索栏-->
<div class="page-header" style="padding-top: 0px;">
<form class="navbar-form" method="get" action="/apisearch/">
 
{% csrf_token %}     
<input type="search" name="apitestname" placeholder="名称" required>
  
<button type="submit">搜索</button>
    

<!-- 增加api流程测试用例-->
<div style="float:right;width:65%">

<select name="Apitest" id="id_Apitest">
<option value="" selected>----api流程接口测试用例----</option>
</select>
<a class="related-widget-wrapper-link change-related" id="change_id_Apitest" data-href-template="/admin/apitest/apitest/__fk__/change/?_to_field=id&amp;_popup=1" title="更改选中的测试用例">
<img src="/static/admin/img/icon-changelink.svg" alt="修改"/>
</a>
<a style='color:light blue' class="related-widget-wrapper-link add-related" id="add_id_Apitest" href="/admin/apitest/apitest/add/?_to_field=id&amp;_popup=1" title="增加另一个 测试用例">
<img src="/static/admin/img/icon-addlink.svg" alt="增加"/>增加
</a>

</form>
</div>

<!-- 流程接口列表-->
<div class="row" style="padding-top: 20px;">
<div class="col-md-12">
<table class="table table-striped">
<thead>

<tr>
<th>ID</th><th>产品</th><th>用例名称</th><th>接口场景描述</th><th>结果</th><th>负责人</th><th>查看</th><th>编辑</th><th>删除</th>
</tr>
</thead>
<tbody>
{% for apitest in apitests %}
<tr>
<td>{{ apitest.id  }}</td>
<td>{{ apitest.Product.productname }}</td>
<td>{{ apitest.apitestname }}</td>
<td>{{ apitest.apitestdesc }}</td>
<td>{% if apitest.apitestresult == 1 %}
<a style='color:green'>{{ apitest.apitestresult }}</a> 
{% else %}
<a style='color:red'>{{ apitest.apitestresult }}</a> 
{% endif %}
</td>
<td>{{ apitest.apitester }}</td>
<td><a href="{% url "apistep_manage" %}?apitest.id={{ apitest.id  }} "><img src="/static/admin/img/icon-yes.svg"/></a></td>
<td><a style='color:light blue' class="related-widget-wrapper-link add-related" id="add_id_Apitest" href="../admin/apitest/apitest/{{ apitest.id  }}/change/?_to_field=id&_popup=1"><img src="/static/admin/img/icon-changelink.svg"/></a></td>
<td><a style='color:light blue' class="related-widget-wrapper-link add-related" id="add_id_Apitest" href="../admin/apitest/apitest/{{ apitest.id  }}/delete/?_to_field=id&_popup=1"><img src="/static/admin/img/icon-deletelink.svg"/></a></td>
</tr>
{% endfor %}
</tbody>
</table>
</div>
</div>
<!--统计和翻页功能-->
<span style="position:absolute; left:600px; bottom:30px;">   {# 把翻页功能固定显示在右下角#}
<div style="position:absolute; right:950px; bottom:25px; width:100px;">
共:{{ apitestcounts }}条记录 {# 前端读取定义的变量#}
</div>
<div class="container">
    <ul class="pagination" id="pager">
          {# 上一页链接开始#}
        {% if apitests.has_previous %}
            {#  如果有上一页则正常显示上一页链接#}
            <li class="previous"><a href="/apitest_manage/?page={{ apitests.previous_page_number }}">上一页</a></li>    {#  上一页标签 #}
        {% else %}
            <li class="previous disabled"><a href="#">上一页</a></li> {# 如果当前不存在上一页则上一页的链接不可点击#}
        {% endif %}
        {# 上一页链接开始#}
        
        {% for num in apitests.paginator.page_range %}
         
            {% if num == currentPage %}
                <li class="item active"><a href="/apitest_manage/?page={{ num }}">{{ num }}</a></li> {#显示当页数链接#} 
            {% else %}
                <li class="item"><a href="/apitest_manage/?page={{ num }}">{{ num }}</a></li>
            {% endif %}
        {% endfor %}
        
        {# 下一页链接开始#}
        {% if apitests.has_next %} {#  如果有下一页则正常显示下一页链接#}
            <li class="next"><a href="/apitest_manage/?page={{ apitests.next_page_number }}">下一页</a></li>
        {% else %}
            <li class="next disabled"><a href="#">下一页</a></li>
        {% endif %}
        {# 下一页链接结束#}
    </ul>
</div>


</body>
</html>

apitest/templates/home.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Frameset//EN" "http://www.w3.org/TR/html4/frameset.dtd">
<html>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<head>
    <title>autotestplat-自动化平台测试开发</title>
</head>
<frameset id="frame1" rows="*" cols="285,*" framespacing="0" frameborder="yes" border="0">
    <frame src="../left" name="leftFrame" scrolling="auto" noresize>
    <frame src="../welcome" name="mainFrame" scrolling="NO" noresize>
</frameset>
<noframes>
    <body>
    </ul>
    <ul class="nav navbar-nav navbar-right">
        <li>欢迎您，<a href="../admin/">{{user}}</a></li>
        <li><a href="/logout/">退出</a></li>
    </ul>
    </body>
</noframes>
</html>

apitest/templates/login.html
<!DOCTYPE html>

<html>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>AutotestPlat</title>
    <style> body{text-align:center} </style>
</head>
<body>
<div>
    <font size="1">
        <h1>《自动化平台测试开发》书</h1>
    </font>
    <form method="post" action="/login/">
        {% csrf_token %}
        <br><a>&nbsp;&nbsp;用户名：</a> <input name="username" type="text" placeholder="admin" ><!--placeholder="test"   value="test"-->
        <br><br>  <a>&nbsp;&nbsp;密 &nbsp;&nbsp; 码：</a> <input name="password" type="password" placeholder="test123456"><!-- placeholder="test123456" value="test123456"-->
        <br>{{ error }}<br>
        &nbsp; <button style="width:220px;height:28px;" id="submit" type="submit">登 录</button>
    </form>
</div>
</body>
</html>

product/templates/product_manage.html
<html lang="zh-CN">
<head>
    {% load bootstrap4 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <title>产品自动化测试平台</title>
</head>
<body role="document">
<!-- 导航栏 -->
<nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="#">&nbsp;</a>
        <ul class="nav justify-content-center"></ul>
        <ul class="nav justify-content-end">
            <li class="nav-link"><a style="color:white" href="#">{{user}}</a></li>
            <li class="nav-link"><a style="color:white" href="/logout/">退出</a></li>
        </ul>
    </div>
</nav>

<!-- 产品列表 -->
<div class="row" style="padding-top: 20px">
    <div class="col-md-11">
        <table class="table table-striped">
            <thead>
            <tr>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <th>ID</th>
                <th>产品名称</th>
                <th>产品描述</th>
                <th>产品负责人</th>
                <th>创建时间</th>
            </tr>
            </thead>
            <tbody>
            {% for product in products %}
            <tr>
                <td>{{product.id}}</td>
                <td>{{product.productname}}</td>
                <td>{{product.productdesc}}</td>
                <td>{{product.producter}}</td>
                <td>{{product.create_time}}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
</body>
</html>